### ISSUE TITLE
v2: leave hiding of redirection page to dev

### ISSUE THREAD

**Issue by xini** [fromholdio/silverstripe-superlinker-redirection#4]
I would remove this extension from the module:
https://github.com/fromholdio/silverstripe-superlinker-redirection/blob/84d2d3265428401d3e7a33266eeba77a56758eb6/_config/config.yml#L7-L8

If the page is not used for a project, this should be configured in the project. I would want it to be visible and usable within a site tree. 
(Also if it's not visible per default, why does it exist in the first place?)

**Comment by dizzystuff** [comment]
It's hiding the OOTB `RedirectorPage` - because that's replaced by the `RedirectionPage` in this module :)

**Comment by dizzystuff** [comment]
And the extension is added to `$extensions` with an array key `fioHiddenPage`, so that it can be removed/nulled if dev chooses - but to hide it is the correct default behaviour IMO. Am open to arguments against this though.

**Comment by xini** [comment]
No of course. Sorry.
